service:
  name: certificates

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  environment:
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
    CERTIFICATES_URL: ${env:CERTIFICATES_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

custom:
  serverless-offline:
    httpPort: 3000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  generate-certificate:
    handler: src/functions/generate-certificate.handle
    events:
      - http:
          path: /generate-certificate
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/certificates"
  verify-certificate:
    handler: src/functions/verify-certificate.handle
    events:
      - http:
          path: /verify-certificate/{id}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/certificates"

resources:
  Resources:
    dbCertificates:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: certificates
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
