version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    env_file: ../.env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
